---
# tasks file for provision
- name: install packages
  apt: name={{item}} state=present
  with_items:
    - git
    - maven

- name: clone a github repository
  git:
    repo: https://github.com/daticahealth/java-tomcat-maven-example.git
    dest: {{dest_folder}}
    clone: yes
    update: yes

- name: running assembly
  shell: "mvn package"
  args:
    chdir: "{{dest_folder}}"