---
# tasks file for prodaction
- name: install packages
  apt: name={{item}} state=present
  with_items:
    - default-jdk
    - tomcat9

- name: copy war file
  copy: src=/tmp/java-tomcat-maven-example.war dest={{dest_folder}}/java-tomcat-maven-example.war

- name: Change war file for tomcat
  file:
    path: "{{dest_folder}}/java-tomcat-maven-example.war"
    owner: tomcat
    group: tomcat
    mode: '0644'
  notify:
    - restart tomcat9  
